# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
    - dependency-name: "openapi-typescript"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Prague"
    commit-message:
      prefix: "npm"
    commit-message:
      prefix: "npm"
