/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/elrhLink": {
    get: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrhLink.linkId"];
          categoryId?: parameters["rowFilter.elrhLink.categoryId"];
          ord?: parameters["rowFilter.elrhLink.ord"];
          dateCreated?: parameters["rowFilter.elrhLink.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhLink.dateEdited"];
          name?: parameters["rowFilter.elrhLink.name"];
          dscr?: parameters["rowFilter.elrhLink.dscr"];
          url?: parameters["rowFilter.elrhLink.url"];
          thumb?: parameters["rowFilter.elrhLink.thumb"];
          authorId?: parameters["rowFilter.elrhLink.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhLink"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhLink */
          elrhLink?: definitions["elrhLink"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrhLink.linkId"];
          categoryId?: parameters["rowFilter.elrhLink.categoryId"];
          ord?: parameters["rowFilter.elrhLink.ord"];
          dateCreated?: parameters["rowFilter.elrhLink.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhLink.dateEdited"];
          name?: parameters["rowFilter.elrhLink.name"];
          dscr?: parameters["rowFilter.elrhLink.dscr"];
          url?: parameters["rowFilter.elrhLink.url"];
          thumb?: parameters["rowFilter.elrhLink.thumb"];
          authorId?: parameters["rowFilter.elrhLink.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrhLink.linkId"];
          categoryId?: parameters["rowFilter.elrhLink.categoryId"];
          ord?: parameters["rowFilter.elrhLink.ord"];
          dateCreated?: parameters["rowFilter.elrhLink.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhLink.dateEdited"];
          name?: parameters["rowFilter.elrhLink.name"];
          dscr?: parameters["rowFilter.elrhLink.dscr"];
          url?: parameters["rowFilter.elrhLink.url"];
          thumb?: parameters["rowFilter.elrhLink.thumb"];
          authorId?: parameters["rowFilter.elrhLink.authorId"];
        };
        body: {
          /** elrhLink */
          elrhLink?: definitions["elrhLink"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhNews": {
    get: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrhNews.newsId"];
          dateCreated?: parameters["rowFilter.elrhNews.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhNews.dateEdited"];
          title?: parameters["rowFilter.elrhNews.title"];
          content?: parameters["rowFilter.elrhNews.content"];
          url?: parameters["rowFilter.elrhNews.url"];
          authorId?: parameters["rowFilter.elrhNews.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhNews"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhNews */
          elrhNews?: definitions["elrhNews"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrhNews.newsId"];
          dateCreated?: parameters["rowFilter.elrhNews.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhNews.dateEdited"];
          title?: parameters["rowFilter.elrhNews.title"];
          content?: parameters["rowFilter.elrhNews.content"];
          url?: parameters["rowFilter.elrhNews.url"];
          authorId?: parameters["rowFilter.elrhNews.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrhNews.newsId"];
          dateCreated?: parameters["rowFilter.elrhNews.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhNews.dateEdited"];
          title?: parameters["rowFilter.elrhNews.title"];
          content?: parameters["rowFilter.elrhNews.content"];
          url?: parameters["rowFilter.elrhNews.url"];
          authorId?: parameters["rowFilter.elrhNews.authorId"];
        };
        body: {
          /** elrhNews */
          elrhNews?: definitions["elrhNews"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhImage": {
    get: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrhImage.imageId"];
          dateCreated?: parameters["rowFilter.elrhImage.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhImage.dateEdited"];
          name?: parameters["rowFilter.elrhImage.name"];
          dscr?: parameters["rowFilter.elrhImage.dscr"];
          authorId?: parameters["rowFilter.elrhImage.authorId"];
          image?: parameters["rowFilter.elrhImage.image"];
          galleryId?: parameters["rowFilter.elrhImage.galleryId"];
          ord?: parameters["rowFilter.elrhImage.ord"];
          prevId?: parameters["rowFilter.elrhImage.prevId"];
          nextId?: parameters["rowFilter.elrhImage.nextId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhImage"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhImage */
          elrhImage?: definitions["elrhImage"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrhImage.imageId"];
          dateCreated?: parameters["rowFilter.elrhImage.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhImage.dateEdited"];
          name?: parameters["rowFilter.elrhImage.name"];
          dscr?: parameters["rowFilter.elrhImage.dscr"];
          authorId?: parameters["rowFilter.elrhImage.authorId"];
          image?: parameters["rowFilter.elrhImage.image"];
          galleryId?: parameters["rowFilter.elrhImage.galleryId"];
          ord?: parameters["rowFilter.elrhImage.ord"];
          prevId?: parameters["rowFilter.elrhImage.prevId"];
          nextId?: parameters["rowFilter.elrhImage.nextId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrhImage.imageId"];
          dateCreated?: parameters["rowFilter.elrhImage.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhImage.dateEdited"];
          name?: parameters["rowFilter.elrhImage.name"];
          dscr?: parameters["rowFilter.elrhImage.dscr"];
          authorId?: parameters["rowFilter.elrhImage.authorId"];
          image?: parameters["rowFilter.elrhImage.image"];
          galleryId?: parameters["rowFilter.elrhImage.galleryId"];
          ord?: parameters["rowFilter.elrhImage.ord"];
          prevId?: parameters["rowFilter.elrhImage.prevId"];
          nextId?: parameters["rowFilter.elrhImage.nextId"];
        };
        body: {
          /** elrhImage */
          elrhImage?: definitions["elrhImage"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhTimeline": {
    get: {
      parameters: {
        query: {
          timelineId?: parameters["rowFilter.elrhTimeline.timelineId"];
          title?: parameters["rowFilter.elrhTimeline.title"];
          content?: parameters["rowFilter.elrhTimeline.content"];
          tooltip?: parameters["rowFilter.elrhTimeline.tooltip"];
          authorId?: parameters["rowFilter.elrhTimeline.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhTimeline"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhTimeline */
          elrhTimeline?: definitions["elrhTimeline"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          timelineId?: parameters["rowFilter.elrhTimeline.timelineId"];
          title?: parameters["rowFilter.elrhTimeline.title"];
          content?: parameters["rowFilter.elrhTimeline.content"];
          tooltip?: parameters["rowFilter.elrhTimeline.tooltip"];
          authorId?: parameters["rowFilter.elrhTimeline.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          timelineId?: parameters["rowFilter.elrhTimeline.timelineId"];
          title?: parameters["rowFilter.elrhTimeline.title"];
          content?: parameters["rowFilter.elrhTimeline.content"];
          tooltip?: parameters["rowFilter.elrhTimeline.tooltip"];
          authorId?: parameters["rowFilter.elrhTimeline.authorId"];
        };
        body: {
          /** elrhTimeline */
          elrhTimeline?: definitions["elrhTimeline"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhArticle": {
    get: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrhArticle.articleId"];
          categoryId?: parameters["rowFilter.elrhArticle.categoryId"];
          dateCreated?: parameters["rowFilter.elrhArticle.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhArticle.dateEdited"];
          name?: parameters["rowFilter.elrhArticle.name"];
          dscr?: parameters["rowFilter.elrhArticle.dscr"];
          content?: parameters["rowFilter.elrhArticle.content"];
          thumb?: parameters["rowFilter.elrhArticle.thumb"];
          authorId?: parameters["rowFilter.elrhArticle.authorId"];
          galleryId?: parameters["rowFilter.elrhArticle.galleryId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhArticle"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhArticle */
          elrhArticle?: definitions["elrhArticle"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrhArticle.articleId"];
          categoryId?: parameters["rowFilter.elrhArticle.categoryId"];
          dateCreated?: parameters["rowFilter.elrhArticle.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhArticle.dateEdited"];
          name?: parameters["rowFilter.elrhArticle.name"];
          dscr?: parameters["rowFilter.elrhArticle.dscr"];
          content?: parameters["rowFilter.elrhArticle.content"];
          thumb?: parameters["rowFilter.elrhArticle.thumb"];
          authorId?: parameters["rowFilter.elrhArticle.authorId"];
          galleryId?: parameters["rowFilter.elrhArticle.galleryId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrhArticle.articleId"];
          categoryId?: parameters["rowFilter.elrhArticle.categoryId"];
          dateCreated?: parameters["rowFilter.elrhArticle.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhArticle.dateEdited"];
          name?: parameters["rowFilter.elrhArticle.name"];
          dscr?: parameters["rowFilter.elrhArticle.dscr"];
          content?: parameters["rowFilter.elrhArticle.content"];
          thumb?: parameters["rowFilter.elrhArticle.thumb"];
          authorId?: parameters["rowFilter.elrhArticle.authorId"];
          galleryId?: parameters["rowFilter.elrhArticle.galleryId"];
        };
        body: {
          /** elrhArticle */
          elrhArticle?: definitions["elrhArticle"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhCategory": {
    get: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrhCategory.categoryId"];
          ord?: parameters["rowFilter.elrhCategory.ord"];
          name?: parameters["rowFilter.elrhCategory.name"];
          dscr?: parameters["rowFilter.elrhCategory.dscr"];
          type?: parameters["rowFilter.elrhCategory.type"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhCategory"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhCategory */
          elrhCategory?: definitions["elrhCategory"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrhCategory.categoryId"];
          ord?: parameters["rowFilter.elrhCategory.ord"];
          name?: parameters["rowFilter.elrhCategory.name"];
          dscr?: parameters["rowFilter.elrhCategory.dscr"];
          type?: parameters["rowFilter.elrhCategory.type"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrhCategory.categoryId"];
          ord?: parameters["rowFilter.elrhCategory.ord"];
          name?: parameters["rowFilter.elrhCategory.name"];
          dscr?: parameters["rowFilter.elrhCategory.dscr"];
          type?: parameters["rowFilter.elrhCategory.type"];
        };
        body: {
          /** elrhCategory */
          elrhCategory?: definitions["elrhCategory"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhAuthor": {
    get: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrhAuthor.authorId"];
          email?: parameters["rowFilter.elrhAuthor.email"];
          name?: parameters["rowFilter.elrhAuthor.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhAuthor"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhAuthor */
          elrhAuthor?: definitions["elrhAuthor"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrhAuthor.authorId"];
          email?: parameters["rowFilter.elrhAuthor.email"];
          name?: parameters["rowFilter.elrhAuthor.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrhAuthor.authorId"];
          email?: parameters["rowFilter.elrhAuthor.email"];
          name?: parameters["rowFilter.elrhAuthor.name"];
        };
        body: {
          /** elrhAuthor */
          elrhAuthor?: definitions["elrhAuthor"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhGallery": {
    get: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrhGallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrhGallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhGallery.dateEdited"];
          name?: parameters["rowFilter.elrhGallery.name"];
          dscr?: parameters["rowFilter.elrhGallery.dscr"];
          authorId?: parameters["rowFilter.elrhGallery.authorId"];
          parentId?: parameters["rowFilter.elrhGallery.parentId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhGallery"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhGallery */
          elrhGallery?: definitions["elrhGallery"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrhGallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrhGallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhGallery.dateEdited"];
          name?: parameters["rowFilter.elrhGallery.name"];
          dscr?: parameters["rowFilter.elrhGallery.dscr"];
          authorId?: parameters["rowFilter.elrhGallery.authorId"];
          parentId?: parameters["rowFilter.elrhGallery.parentId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrhGallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrhGallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhGallery.dateEdited"];
          name?: parameters["rowFilter.elrhGallery.name"];
          dscr?: parameters["rowFilter.elrhGallery.dscr"];
          authorId?: parameters["rowFilter.elrhGallery.authorId"];
          parentId?: parameters["rowFilter.elrhGallery.parentId"];
        };
        body: {
          /** elrhGallery */
          elrhGallery?: definitions["elrhGallery"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhBook": {
    get: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrhBook.bookId"];
          categoryId?: parameters["rowFilter.elrhBook.categoryId"];
          ord?: parameters["rowFilter.elrhBook.ord"];
          dateCreated?: parameters["rowFilter.elrhBook.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhBook.dateEdited"];
          writer?: parameters["rowFilter.elrhBook.writer"];
          name?: parameters["rowFilter.elrhBook.name"];
          dscr?: parameters["rowFilter.elrhBook.dscr"];
          url?: parameters["rowFilter.elrhBook.url"];
          thumb?: parameters["rowFilter.elrhBook.thumb"];
          review?: parameters["rowFilter.elrhBook.review"];
          year?: parameters["rowFilter.elrhBook.year"];
          authorId?: parameters["rowFilter.elrhBook.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhBook"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhBook */
          elrhBook?: definitions["elrhBook"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrhBook.bookId"];
          categoryId?: parameters["rowFilter.elrhBook.categoryId"];
          ord?: parameters["rowFilter.elrhBook.ord"];
          dateCreated?: parameters["rowFilter.elrhBook.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhBook.dateEdited"];
          writer?: parameters["rowFilter.elrhBook.writer"];
          name?: parameters["rowFilter.elrhBook.name"];
          dscr?: parameters["rowFilter.elrhBook.dscr"];
          url?: parameters["rowFilter.elrhBook.url"];
          thumb?: parameters["rowFilter.elrhBook.thumb"];
          review?: parameters["rowFilter.elrhBook.review"];
          year?: parameters["rowFilter.elrhBook.year"];
          authorId?: parameters["rowFilter.elrhBook.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrhBook.bookId"];
          categoryId?: parameters["rowFilter.elrhBook.categoryId"];
          ord?: parameters["rowFilter.elrhBook.ord"];
          dateCreated?: parameters["rowFilter.elrhBook.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhBook.dateEdited"];
          writer?: parameters["rowFilter.elrhBook.writer"];
          name?: parameters["rowFilter.elrhBook.name"];
          dscr?: parameters["rowFilter.elrhBook.dscr"];
          url?: parameters["rowFilter.elrhBook.url"];
          thumb?: parameters["rowFilter.elrhBook.thumb"];
          review?: parameters["rowFilter.elrhBook.review"];
          year?: parameters["rowFilter.elrhBook.year"];
          authorId?: parameters["rowFilter.elrhBook.authorId"];
        };
        body: {
          /** elrhBook */
          elrhBook?: definitions["elrhBook"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhContact": {
    get: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrhContact.contactId"];
          name?: parameters["rowFilter.elrhContact.name"];
          email?: parameters["rowFilter.elrhContact.email"];
          phone?: parameters["rowFilter.elrhContact.phone"];
          fb?: parameters["rowFilter.elrhContact.fb"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhContact"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhContact */
          elrhContact?: definitions["elrhContact"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrhContact.contactId"];
          name?: parameters["rowFilter.elrhContact.name"];
          email?: parameters["rowFilter.elrhContact.email"];
          phone?: parameters["rowFilter.elrhContact.phone"];
          fb?: parameters["rowFilter.elrhContact.fb"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrhContact.contactId"];
          name?: parameters["rowFilter.elrhContact.name"];
          email?: parameters["rowFilter.elrhContact.email"];
          phone?: parameters["rowFilter.elrhContact.phone"];
          fb?: parameters["rowFilter.elrhContact.fb"];
        };
        body: {
          /** elrhContact */
          elrhContact?: definitions["elrhContact"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  elrhLink: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    linkId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhCategory.categoryId`.<fk table='elrhCategory' column='categoryId'/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
  };
  elrhNews: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    newsId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    title: string;
    /** Format: text */
    content: string;
    /** Format: character varying */
    url?: string;
    /** Format: integer */
    authorId: number;
  };
  elrhImage: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    imageId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
    /** Format: character varying */
    image: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhGallery.galleryId`.<fk table='elrhGallery' column='galleryId'/>
     */
    galleryId: number;
    /** Format: integer */
    ord: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhImage.imageId`.<fk table='elrhImage' column='imageId'/>
     */
    prevId?: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhImage.imageId`.<fk table='elrhImage' column='imageId'/>
     */
    nextId?: number;
  };
  elrhTimeline: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    timelineId: number;
    /** Format: character varying */
    title: string;
    /** Format: character varying */
    content: string;
    /** Format: text */
    tooltip?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
  };
  elrhArticle: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    articleId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhCategory.categoryId`.<fk table='elrhCategory' column='categoryId'/>
     */
    categoryId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: text */
    content: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhGallery.galleryId`.<fk table='elrhGallery' column='galleryId'/>
     */
    galleryId?: number;
  };
  elrhCategory: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    type: string;
  };
  elrhAuthor: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    authorId: number;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    name: string;
  };
  elrhGallery: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    galleryId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhGallery.galleryId`.<fk table='elrhGallery' column='galleryId'/>
     */
    parentId?: number;
  };
  elrhBook: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    bookId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhCategory.categoryId`.<fk table='elrhCategory' column='categoryId'/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    writer: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /** Format: character varying */
    review?: string;
    /** Format: character varying */
    year: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
  };
  elrhContact: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    contactId: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    phone: string;
    /** Format: character varying */
    fb?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferPost:
    | "return=representation"
    | "return=minimal"
    | "return=none"
    | "resolution=ignore-duplicates"
    | "resolution=merge-duplicates";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description elrhLink */
  "body.elrhLink": definitions["elrhLink"];
  /** Format: integer */
  "rowFilter.elrhLink.linkId": string;
  /** Format: integer */
  "rowFilter.elrhLink.categoryId": string;
  /** Format: integer */
  "rowFilter.elrhLink.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhLink.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhLink.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhLink.name": string;
  /** Format: character varying */
  "rowFilter.elrhLink.dscr": string;
  /** Format: character varying */
  "rowFilter.elrhLink.url": string;
  /** Format: character varying */
  "rowFilter.elrhLink.thumb": string;
  /** Format: integer */
  "rowFilter.elrhLink.authorId": string;
  /** @description elrhNews */
  "body.elrhNews": definitions["elrhNews"];
  /** Format: integer */
  "rowFilter.elrhNews.newsId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhNews.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhNews.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhNews.title": string;
  /** Format: text */
  "rowFilter.elrhNews.content": string;
  /** Format: character varying */
  "rowFilter.elrhNews.url": string;
  /** Format: integer */
  "rowFilter.elrhNews.authorId": string;
  /** @description elrhImage */
  "body.elrhImage": definitions["elrhImage"];
  /** Format: integer */
  "rowFilter.elrhImage.imageId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhImage.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhImage.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhImage.name": string;
  /** Format: text */
  "rowFilter.elrhImage.dscr": string;
  /** Format: integer */
  "rowFilter.elrhImage.authorId": string;
  /** Format: character varying */
  "rowFilter.elrhImage.image": string;
  /** Format: integer */
  "rowFilter.elrhImage.galleryId": string;
  /** Format: integer */
  "rowFilter.elrhImage.ord": string;
  /** Format: integer */
  "rowFilter.elrhImage.prevId": string;
  /** Format: integer */
  "rowFilter.elrhImage.nextId": string;
  /** @description elrhTimeline */
  "body.elrhTimeline": definitions["elrhTimeline"];
  /** Format: integer */
  "rowFilter.elrhTimeline.timelineId": string;
  /** Format: character varying */
  "rowFilter.elrhTimeline.title": string;
  /** Format: character varying */
  "rowFilter.elrhTimeline.content": string;
  /** Format: text */
  "rowFilter.elrhTimeline.tooltip": string;
  /** Format: integer */
  "rowFilter.elrhTimeline.authorId": string;
  /** @description elrhArticle */
  "body.elrhArticle": definitions["elrhArticle"];
  /** Format: integer */
  "rowFilter.elrhArticle.articleId": string;
  /** Format: integer */
  "rowFilter.elrhArticle.categoryId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhArticle.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhArticle.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhArticle.name": string;
  /** Format: character varying */
  "rowFilter.elrhArticle.dscr": string;
  /** Format: text */
  "rowFilter.elrhArticle.content": string;
  /** Format: character varying */
  "rowFilter.elrhArticle.thumb": string;
  /** Format: integer */
  "rowFilter.elrhArticle.authorId": string;
  /** Format: integer */
  "rowFilter.elrhArticle.galleryId": string;
  /** @description elrhCategory */
  "body.elrhCategory": definitions["elrhCategory"];
  /** Format: integer */
  "rowFilter.elrhCategory.categoryId": string;
  /** Format: integer */
  "rowFilter.elrhCategory.ord": string;
  /** Format: character varying */
  "rowFilter.elrhCategory.name": string;
  /** Format: character varying */
  "rowFilter.elrhCategory.dscr": string;
  /** Format: character varying */
  "rowFilter.elrhCategory.type": string;
  /** @description elrhAuthor */
  "body.elrhAuthor": definitions["elrhAuthor"];
  /** Format: integer */
  "rowFilter.elrhAuthor.authorId": string;
  /** Format: character varying */
  "rowFilter.elrhAuthor.email": string;
  /** Format: character varying */
  "rowFilter.elrhAuthor.name": string;
  /** @description elrhGallery */
  "body.elrhGallery": definitions["elrhGallery"];
  /** Format: integer */
  "rowFilter.elrhGallery.galleryId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhGallery.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhGallery.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhGallery.name": string;
  /** Format: text */
  "rowFilter.elrhGallery.dscr": string;
  /** Format: integer */
  "rowFilter.elrhGallery.authorId": string;
  /** Format: integer */
  "rowFilter.elrhGallery.parentId": string;
  /** @description elrhBook */
  "body.elrhBook": definitions["elrhBook"];
  /** Format: integer */
  "rowFilter.elrhBook.bookId": string;
  /** Format: integer */
  "rowFilter.elrhBook.categoryId": string;
  /** Format: integer */
  "rowFilter.elrhBook.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhBook.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhBook.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhBook.writer": string;
  /** Format: character varying */
  "rowFilter.elrhBook.name": string;
  /** Format: character varying */
  "rowFilter.elrhBook.dscr": string;
  /** Format: character varying */
  "rowFilter.elrhBook.url": string;
  /** Format: character varying */
  "rowFilter.elrhBook.thumb": string;
  /** Format: character varying */
  "rowFilter.elrhBook.review": string;
  /** Format: character varying */
  "rowFilter.elrhBook.year": string;
  /** Format: integer */
  "rowFilter.elrhBook.authorId": string;
  /** @description elrhContact */
  "body.elrhContact": definitions["elrhContact"];
  /** Format: integer */
  "rowFilter.elrhContact.contactId": string;
  /** Format: character varying */
  "rowFilter.elrhContact.name": string;
  /** Format: character varying */
  "rowFilter.elrhContact.email": string;
  /** Format: character varying */
  "rowFilter.elrhContact.phone": string;
  /** Format: character varying */
  "rowFilter.elrhContact.fb": string;
}

export interface operations {}

export interface external {}
