/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/elrh_article": {
    get: {
      parameters: {
        query: {
          article_id?: parameters["rowFilter.elrh_article.article_id"];
          category_id?: parameters["rowFilter.elrh_article.category_id"];
          date_created?: parameters["rowFilter.elrh_article.date_created"];
          date_edited?: parameters["rowFilter.elrh_article.date_edited"];
          name?: parameters["rowFilter.elrh_article.name"];
          dscr?: parameters["rowFilter.elrh_article.dscr"];
          content?: parameters["rowFilter.elrh_article.content"];
          thumb?: parameters["rowFilter.elrh_article.thumb"];
          author_id?: parameters["rowFilter.elrh_article.author_id"];
          gallery_id?: parameters["rowFilter.elrh_article.gallery_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_article"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_article */
          elrh_article?: definitions["elrh_article"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          article_id?: parameters["rowFilter.elrh_article.article_id"];
          category_id?: parameters["rowFilter.elrh_article.category_id"];
          date_created?: parameters["rowFilter.elrh_article.date_created"];
          date_edited?: parameters["rowFilter.elrh_article.date_edited"];
          name?: parameters["rowFilter.elrh_article.name"];
          dscr?: parameters["rowFilter.elrh_article.dscr"];
          content?: parameters["rowFilter.elrh_article.content"];
          thumb?: parameters["rowFilter.elrh_article.thumb"];
          author_id?: parameters["rowFilter.elrh_article.author_id"];
          gallery_id?: parameters["rowFilter.elrh_article.gallery_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          article_id?: parameters["rowFilter.elrh_article.article_id"];
          category_id?: parameters["rowFilter.elrh_article.category_id"];
          date_created?: parameters["rowFilter.elrh_article.date_created"];
          date_edited?: parameters["rowFilter.elrh_article.date_edited"];
          name?: parameters["rowFilter.elrh_article.name"];
          dscr?: parameters["rowFilter.elrh_article.dscr"];
          content?: parameters["rowFilter.elrh_article.content"];
          thumb?: parameters["rowFilter.elrh_article.thumb"];
          author_id?: parameters["rowFilter.elrh_article.author_id"];
          gallery_id?: parameters["rowFilter.elrh_article.gallery_id"];
        };
        body: {
          /** elrh_article */
          elrh_article?: definitions["elrh_article"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_contact": {
    get: {
      parameters: {
        query: {
          contact_id?: parameters["rowFilter.elrh_contact.contact_id"];
          name?: parameters["rowFilter.elrh_contact.name"];
          email?: parameters["rowFilter.elrh_contact.email"];
          phone?: parameters["rowFilter.elrh_contact.phone"];
          fb?: parameters["rowFilter.elrh_contact.fb"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_contact"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_contact */
          elrh_contact?: definitions["elrh_contact"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          contact_id?: parameters["rowFilter.elrh_contact.contact_id"];
          name?: parameters["rowFilter.elrh_contact.name"];
          email?: parameters["rowFilter.elrh_contact.email"];
          phone?: parameters["rowFilter.elrh_contact.phone"];
          fb?: parameters["rowFilter.elrh_contact.fb"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          contact_id?: parameters["rowFilter.elrh_contact.contact_id"];
          name?: parameters["rowFilter.elrh_contact.name"];
          email?: parameters["rowFilter.elrh_contact.email"];
          phone?: parameters["rowFilter.elrh_contact.phone"];
          fb?: parameters["rowFilter.elrh_contact.fb"];
        };
        body: {
          /** elrh_contact */
          elrh_contact?: definitions["elrh_contact"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_gallery": {
    get: {
      parameters: {
        query: {
          gallery_id?: parameters["rowFilter.elrh_gallery.gallery_id"];
          date_created?: parameters["rowFilter.elrh_gallery.date_created"];
          date_edited?: parameters["rowFilter.elrh_gallery.date_edited"];
          name?: parameters["rowFilter.elrh_gallery.name"];
          dscr?: parameters["rowFilter.elrh_gallery.dscr"];
          author_id?: parameters["rowFilter.elrh_gallery.author_id"];
          parent_id?: parameters["rowFilter.elrh_gallery.parent_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_gallery"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_gallery */
          elrh_gallery?: definitions["elrh_gallery"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          gallery_id?: parameters["rowFilter.elrh_gallery.gallery_id"];
          date_created?: parameters["rowFilter.elrh_gallery.date_created"];
          date_edited?: parameters["rowFilter.elrh_gallery.date_edited"];
          name?: parameters["rowFilter.elrh_gallery.name"];
          dscr?: parameters["rowFilter.elrh_gallery.dscr"];
          author_id?: parameters["rowFilter.elrh_gallery.author_id"];
          parent_id?: parameters["rowFilter.elrh_gallery.parent_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          gallery_id?: parameters["rowFilter.elrh_gallery.gallery_id"];
          date_created?: parameters["rowFilter.elrh_gallery.date_created"];
          date_edited?: parameters["rowFilter.elrh_gallery.date_edited"];
          name?: parameters["rowFilter.elrh_gallery.name"];
          dscr?: parameters["rowFilter.elrh_gallery.dscr"];
          author_id?: parameters["rowFilter.elrh_gallery.author_id"];
          parent_id?: parameters["rowFilter.elrh_gallery.parent_id"];
        };
        body: {
          /** elrh_gallery */
          elrh_gallery?: definitions["elrh_gallery"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_author": {
    get: {
      parameters: {
        query: {
          author_id?: parameters["rowFilter.elrh_author.author_id"];
          email?: parameters["rowFilter.elrh_author.email"];
          name?: parameters["rowFilter.elrh_author.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_author"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_author */
          elrh_author?: definitions["elrh_author"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          author_id?: parameters["rowFilter.elrh_author.author_id"];
          email?: parameters["rowFilter.elrh_author.email"];
          name?: parameters["rowFilter.elrh_author.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          author_id?: parameters["rowFilter.elrh_author.author_id"];
          email?: parameters["rowFilter.elrh_author.email"];
          name?: parameters["rowFilter.elrh_author.name"];
        };
        body: {
          /** elrh_author */
          elrh_author?: definitions["elrh_author"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_link": {
    get: {
      parameters: {
        query: {
          link_id?: parameters["rowFilter.elrh_link.link_id"];
          category_id?: parameters["rowFilter.elrh_link.category_id"];
          ord?: parameters["rowFilter.elrh_link.ord"];
          date_created?: parameters["rowFilter.elrh_link.date_created"];
          date_edited?: parameters["rowFilter.elrh_link.date_edited"];
          name?: parameters["rowFilter.elrh_link.name"];
          dscr?: parameters["rowFilter.elrh_link.dscr"];
          url?: parameters["rowFilter.elrh_link.url"];
          thumb?: parameters["rowFilter.elrh_link.thumb"];
          author_id?: parameters["rowFilter.elrh_link.author_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_link"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_link */
          elrh_link?: definitions["elrh_link"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          link_id?: parameters["rowFilter.elrh_link.link_id"];
          category_id?: parameters["rowFilter.elrh_link.category_id"];
          ord?: parameters["rowFilter.elrh_link.ord"];
          date_created?: parameters["rowFilter.elrh_link.date_created"];
          date_edited?: parameters["rowFilter.elrh_link.date_edited"];
          name?: parameters["rowFilter.elrh_link.name"];
          dscr?: parameters["rowFilter.elrh_link.dscr"];
          url?: parameters["rowFilter.elrh_link.url"];
          thumb?: parameters["rowFilter.elrh_link.thumb"];
          author_id?: parameters["rowFilter.elrh_link.author_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          link_id?: parameters["rowFilter.elrh_link.link_id"];
          category_id?: parameters["rowFilter.elrh_link.category_id"];
          ord?: parameters["rowFilter.elrh_link.ord"];
          date_created?: parameters["rowFilter.elrh_link.date_created"];
          date_edited?: parameters["rowFilter.elrh_link.date_edited"];
          name?: parameters["rowFilter.elrh_link.name"];
          dscr?: parameters["rowFilter.elrh_link.dscr"];
          url?: parameters["rowFilter.elrh_link.url"];
          thumb?: parameters["rowFilter.elrh_link.thumb"];
          author_id?: parameters["rowFilter.elrh_link.author_id"];
        };
        body: {
          /** elrh_link */
          elrh_link?: definitions["elrh_link"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_image": {
    get: {
      parameters: {
        query: {
          image_id?: parameters["rowFilter.elrh_image.image_id"];
          date_created?: parameters["rowFilter.elrh_image.date_created"];
          date_edited?: parameters["rowFilter.elrh_image.date_edited"];
          name?: parameters["rowFilter.elrh_image.name"];
          dscr?: parameters["rowFilter.elrh_image.dscr"];
          author_id?: parameters["rowFilter.elrh_image.author_id"];
          image?: parameters["rowFilter.elrh_image.image"];
          gallery_id?: parameters["rowFilter.elrh_image.gallery_id"];
          ord?: parameters["rowFilter.elrh_image.ord"];
          prev_id?: parameters["rowFilter.elrh_image.prev_id"];
          next_id?: parameters["rowFilter.elrh_image.next_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_image"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_image */
          elrh_image?: definitions["elrh_image"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          image_id?: parameters["rowFilter.elrh_image.image_id"];
          date_created?: parameters["rowFilter.elrh_image.date_created"];
          date_edited?: parameters["rowFilter.elrh_image.date_edited"];
          name?: parameters["rowFilter.elrh_image.name"];
          dscr?: parameters["rowFilter.elrh_image.dscr"];
          author_id?: parameters["rowFilter.elrh_image.author_id"];
          image?: parameters["rowFilter.elrh_image.image"];
          gallery_id?: parameters["rowFilter.elrh_image.gallery_id"];
          ord?: parameters["rowFilter.elrh_image.ord"];
          prev_id?: parameters["rowFilter.elrh_image.prev_id"];
          next_id?: parameters["rowFilter.elrh_image.next_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          image_id?: parameters["rowFilter.elrh_image.image_id"];
          date_created?: parameters["rowFilter.elrh_image.date_created"];
          date_edited?: parameters["rowFilter.elrh_image.date_edited"];
          name?: parameters["rowFilter.elrh_image.name"];
          dscr?: parameters["rowFilter.elrh_image.dscr"];
          author_id?: parameters["rowFilter.elrh_image.author_id"];
          image?: parameters["rowFilter.elrh_image.image"];
          gallery_id?: parameters["rowFilter.elrh_image.gallery_id"];
          ord?: parameters["rowFilter.elrh_image.ord"];
          prev_id?: parameters["rowFilter.elrh_image.prev_id"];
          next_id?: parameters["rowFilter.elrh_image.next_id"];
        };
        body: {
          /** elrh_image */
          elrh_image?: definitions["elrh_image"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_news": {
    get: {
      parameters: {
        query: {
          news_id?: parameters["rowFilter.elrh_news.news_id"];
          content?: parameters["rowFilter.elrh_news.content"];
          author_id?: parameters["rowFilter.elrh_news.author_id"];
          date_created?: parameters["rowFilter.elrh_news.date_created"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_news"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_news */
          elrh_news?: definitions["elrh_news"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          news_id?: parameters["rowFilter.elrh_news.news_id"];
          content?: parameters["rowFilter.elrh_news.content"];
          author_id?: parameters["rowFilter.elrh_news.author_id"];
          date_created?: parameters["rowFilter.elrh_news.date_created"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          news_id?: parameters["rowFilter.elrh_news.news_id"];
          content?: parameters["rowFilter.elrh_news.content"];
          author_id?: parameters["rowFilter.elrh_news.author_id"];
          date_created?: parameters["rowFilter.elrh_news.date_created"];
        };
        body: {
          /** elrh_news */
          elrh_news?: definitions["elrh_news"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_text": {
    get: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrh_text.key"];
          value?: parameters["rowFilter.elrh_text.value"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_text"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_text */
          elrh_text?: definitions["elrh_text"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrh_text.key"];
          value?: parameters["rowFilter.elrh_text.value"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrh_text.key"];
          value?: parameters["rowFilter.elrh_text.value"];
        };
        body: {
          /** elrh_text */
          elrh_text?: definitions["elrh_text"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_category": {
    get: {
      parameters: {
        query: {
          category_id?: parameters["rowFilter.elrh_category.category_id"];
          ord?: parameters["rowFilter.elrh_category.ord"];
          name?: parameters["rowFilter.elrh_category.name"];
          dscr?: parameters["rowFilter.elrh_category.dscr"];
          type?: parameters["rowFilter.elrh_category.type"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_category"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_category */
          elrh_category?: definitions["elrh_category"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          category_id?: parameters["rowFilter.elrh_category.category_id"];
          ord?: parameters["rowFilter.elrh_category.ord"];
          name?: parameters["rowFilter.elrh_category.name"];
          dscr?: parameters["rowFilter.elrh_category.dscr"];
          type?: parameters["rowFilter.elrh_category.type"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          category_id?: parameters["rowFilter.elrh_category.category_id"];
          ord?: parameters["rowFilter.elrh_category.ord"];
          name?: parameters["rowFilter.elrh_category.name"];
          dscr?: parameters["rowFilter.elrh_category.dscr"];
          type?: parameters["rowFilter.elrh_category.type"];
        };
        body: {
          /** elrh_category */
          elrh_category?: definitions["elrh_category"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_book": {
    get: {
      parameters: {
        query: {
          book_id?: parameters["rowFilter.elrh_book.book_id"];
          category_id?: parameters["rowFilter.elrh_book.category_id"];
          ord?: parameters["rowFilter.elrh_book.ord"];
          date_created?: parameters["rowFilter.elrh_book.date_created"];
          date_edited?: parameters["rowFilter.elrh_book.date_edited"];
          writer?: parameters["rowFilter.elrh_book.writer"];
          name?: parameters["rowFilter.elrh_book.name"];
          dscr?: parameters["rowFilter.elrh_book.dscr"];
          url?: parameters["rowFilter.elrh_book.url"];
          thumb?: parameters["rowFilter.elrh_book.thumb"];
          review?: parameters["rowFilter.elrh_book.review"];
          year?: parameters["rowFilter.elrh_book.year"];
          author_id?: parameters["rowFilter.elrh_book.author_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_book"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_book */
          elrh_book?: definitions["elrh_book"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          book_id?: parameters["rowFilter.elrh_book.book_id"];
          category_id?: parameters["rowFilter.elrh_book.category_id"];
          ord?: parameters["rowFilter.elrh_book.ord"];
          date_created?: parameters["rowFilter.elrh_book.date_created"];
          date_edited?: parameters["rowFilter.elrh_book.date_edited"];
          writer?: parameters["rowFilter.elrh_book.writer"];
          name?: parameters["rowFilter.elrh_book.name"];
          dscr?: parameters["rowFilter.elrh_book.dscr"];
          url?: parameters["rowFilter.elrh_book.url"];
          thumb?: parameters["rowFilter.elrh_book.thumb"];
          review?: parameters["rowFilter.elrh_book.review"];
          year?: parameters["rowFilter.elrh_book.year"];
          author_id?: parameters["rowFilter.elrh_book.author_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          book_id?: parameters["rowFilter.elrh_book.book_id"];
          category_id?: parameters["rowFilter.elrh_book.category_id"];
          ord?: parameters["rowFilter.elrh_book.ord"];
          date_created?: parameters["rowFilter.elrh_book.date_created"];
          date_edited?: parameters["rowFilter.elrh_book.date_edited"];
          writer?: parameters["rowFilter.elrh_book.writer"];
          name?: parameters["rowFilter.elrh_book.name"];
          dscr?: parameters["rowFilter.elrh_book.dscr"];
          url?: parameters["rowFilter.elrh_book.url"];
          thumb?: parameters["rowFilter.elrh_book.thumb"];
          review?: parameters["rowFilter.elrh_book.review"];
          year?: parameters["rowFilter.elrh_book.year"];
          author_id?: parameters["rowFilter.elrh_book.author_id"];
        };
        body: {
          /** elrh_book */
          elrh_book?: definitions["elrh_book"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  elrh_article: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    article_id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_category.category_id`.<fk table='elrh_category' column='category_id'/>
     */
    category_id: number;
    /** Format: timestamp without time zone */
    date_created: string;
    /** Format: timestamp without time zone */
    date_edited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: text */
    content: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.author_id`.<fk table='elrh_author' column='author_id'/>
     */
    author_id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_gallery.gallery_id`.<fk table='elrh_gallery' column='gallery_id'/>
     */
    gallery_id?: number;
  };
  elrh_contact: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    contact_id: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    phone: string;
    /** Format: character varying */
    fb: string;
  };
  elrh_gallery: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    gallery_id: number;
    /** Format: timestamp without time zone */
    date_created: string;
    /** Format: timestamp without time zone */
    date_edited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.author_id`.<fk table='elrh_author' column='author_id'/>
     */
    author_id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_gallery.gallery_id`.<fk table='elrh_gallery' column='gallery_id'/>
     */
    parent_id?: number;
  };
  elrh_author: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    author_id: number;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    name: string;
  };
  elrh_link: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    link_id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_category.category_id`.<fk table='elrh_category' column='category_id'/>
     */
    category_id: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    date_created: string;
    /** Format: timestamp without time zone */
    date_edited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.author_id`.<fk table='elrh_author' column='author_id'/>
     */
    author_id: number;
  };
  elrh_image: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    image_id: number;
    /** Format: timestamp without time zone */
    date_created: string;
    /** Format: timestamp without time zone */
    date_edited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.author_id`.<fk table='elrh_author' column='author_id'/>
     */
    author_id: number;
    /** Format: character varying */
    image: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_gallery.gallery_id`.<fk table='elrh_gallery' column='gallery_id'/>
     */
    gallery_id: number;
    /** Format: integer */
    ord: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_image.image_id`.<fk table='elrh_image' column='image_id'/>
     */
    prev_id?: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_image.image_id`.<fk table='elrh_image' column='image_id'/>
     */
    next_id?: number;
  };
  elrh_news: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    news_id: number;
    /** Format: text */
    content: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.author_id`.<fk table='elrh_author' column='author_id'/>
     */
    author_id: number;
    /** Format: timestamp without time zone */
    date_created: string;
  };
  elrh_text: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    key: string;
    /** Format: text */
    value: string;
  };
  elrh_category: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    category_id: number;
    /** Format: integer */
    ord: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    type: string;
  };
  elrh_book: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    book_id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_category.category_id`.<fk table='elrh_category' column='category_id'/>
     */
    category_id: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    date_created: string;
    /** Format: timestamp without time zone */
    date_edited: string;
    /** Format: character varying */
    writer: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /** Format: character varying */
    review?: string;
    /** Format: character varying */
    year: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.author_id`.<fk table='elrh_author' column='author_id'/>
     */
    author_id: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description elrh_article */
  "body.elrh_article": definitions["elrh_article"];
  /** Format: integer */
  "rowFilter.elrh_article.article_id": string;
  /** Format: integer */
  "rowFilter.elrh_article.category_id": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_article.date_created": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_article.date_edited": string;
  /** Format: character varying */
  "rowFilter.elrh_article.name": string;
  /** Format: character varying */
  "rowFilter.elrh_article.dscr": string;
  /** Format: text */
  "rowFilter.elrh_article.content": string;
  /** Format: character varying */
  "rowFilter.elrh_article.thumb": string;
  /** Format: integer */
  "rowFilter.elrh_article.author_id": string;
  /** Format: integer */
  "rowFilter.elrh_article.gallery_id": string;
  /** @description elrh_contact */
  "body.elrh_contact": definitions["elrh_contact"];
  /** Format: integer */
  "rowFilter.elrh_contact.contact_id": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.name": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.email": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.phone": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.fb": string;
  /** @description elrh_gallery */
  "body.elrh_gallery": definitions["elrh_gallery"];
  /** Format: integer */
  "rowFilter.elrh_gallery.gallery_id": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_gallery.date_created": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_gallery.date_edited": string;
  /** Format: character varying */
  "rowFilter.elrh_gallery.name": string;
  /** Format: text */
  "rowFilter.elrh_gallery.dscr": string;
  /** Format: integer */
  "rowFilter.elrh_gallery.author_id": string;
  /** Format: integer */
  "rowFilter.elrh_gallery.parent_id": string;
  /** @description elrh_author */
  "body.elrh_author": definitions["elrh_author"];
  /** Format: integer */
  "rowFilter.elrh_author.author_id": string;
  /** Format: character varying */
  "rowFilter.elrh_author.email": string;
  /** Format: character varying */
  "rowFilter.elrh_author.name": string;
  /** @description elrh_link */
  "body.elrh_link": definitions["elrh_link"];
  /** Format: integer */
  "rowFilter.elrh_link.link_id": string;
  /** Format: integer */
  "rowFilter.elrh_link.category_id": string;
  /** Format: integer */
  "rowFilter.elrh_link.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_link.date_created": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_link.date_edited": string;
  /** Format: character varying */
  "rowFilter.elrh_link.name": string;
  /** Format: character varying */
  "rowFilter.elrh_link.dscr": string;
  /** Format: character varying */
  "rowFilter.elrh_link.url": string;
  /** Format: character varying */
  "rowFilter.elrh_link.thumb": string;
  /** Format: integer */
  "rowFilter.elrh_link.author_id": string;
  /** @description elrh_image */
  "body.elrh_image": definitions["elrh_image"];
  /** Format: integer */
  "rowFilter.elrh_image.image_id": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_image.date_created": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_image.date_edited": string;
  /** Format: character varying */
  "rowFilter.elrh_image.name": string;
  /** Format: text */
  "rowFilter.elrh_image.dscr": string;
  /** Format: integer */
  "rowFilter.elrh_image.author_id": string;
  /** Format: character varying */
  "rowFilter.elrh_image.image": string;
  /** Format: integer */
  "rowFilter.elrh_image.gallery_id": string;
  /** Format: integer */
  "rowFilter.elrh_image.ord": string;
  /** Format: integer */
  "rowFilter.elrh_image.prev_id": string;
  /** Format: integer */
  "rowFilter.elrh_image.next_id": string;
  /** @description elrh_news */
  "body.elrh_news": definitions["elrh_news"];
  /** Format: integer */
  "rowFilter.elrh_news.news_id": string;
  /** Format: text */
  "rowFilter.elrh_news.content": string;
  /** Format: integer */
  "rowFilter.elrh_news.author_id": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_news.date_created": string;
  /** @description elrh_text */
  "body.elrh_text": definitions["elrh_text"];
  /** Format: text */
  "rowFilter.elrh_text.key": string;
  /** Format: text */
  "rowFilter.elrh_text.value": string;
  /** @description elrh_category */
  "body.elrh_category": definitions["elrh_category"];
  /** Format: integer */
  "rowFilter.elrh_category.category_id": string;
  /** Format: integer */
  "rowFilter.elrh_category.ord": string;
  /** Format: character varying */
  "rowFilter.elrh_category.name": string;
  /** Format: character varying */
  "rowFilter.elrh_category.dscr": string;
  /** Format: character varying */
  "rowFilter.elrh_category.type": string;
  /** @description elrh_book */
  "body.elrh_book": definitions["elrh_book"];
  /** Format: integer */
  "rowFilter.elrh_book.book_id": string;
  /** Format: integer */
  "rowFilter.elrh_book.category_id": string;
  /** Format: integer */
  "rowFilter.elrh_book.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_book.date_created": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_book.date_edited": string;
  /** Format: character varying */
  "rowFilter.elrh_book.writer": string;
  /** Format: character varying */
  "rowFilter.elrh_book.name": string;
  /** Format: character varying */
  "rowFilter.elrh_book.dscr": string;
  /** Format: character varying */
  "rowFilter.elrh_book.url": string;
  /** Format: character varying */
  "rowFilter.elrh_book.thumb": string;
  /** Format: character varying */
  "rowFilter.elrh_book.review": string;
  /** Format: character varying */
  "rowFilter.elrh_book.year": string;
  /** Format: integer */
  "rowFilter.elrh_book.author_id": string;
}

export interface operations {}

export interface external {}
