/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/elrhContact": {
    get: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrhContact.contactId"];
          name?: parameters["rowFilter.elrhContact.name"];
          email?: parameters["rowFilter.elrhContact.email"];
          phone?: parameters["rowFilter.elrhContact.phone"];
          fb?: parameters["rowFilter.elrhContact.fb"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhContact"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhContact */
          elrhContact?: definitions["elrhContact"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrhContact.contactId"];
          name?: parameters["rowFilter.elrhContact.name"];
          email?: parameters["rowFilter.elrhContact.email"];
          phone?: parameters["rowFilter.elrhContact.phone"];
          fb?: parameters["rowFilter.elrhContact.fb"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrhContact.contactId"];
          name?: parameters["rowFilter.elrhContact.name"];
          email?: parameters["rowFilter.elrhContact.email"];
          phone?: parameters["rowFilter.elrhContact.phone"];
          fb?: parameters["rowFilter.elrhContact.fb"];
        };
        body: {
          /** elrhContact */
          elrhContact?: definitions["elrhContact"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_article": {
    get: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrh_article.articleId"];
          categoryId?: parameters["rowFilter.elrh_article.categoryId"];
          dateCreated?: parameters["rowFilter.elrh_article.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_article.dateEdited"];
          name?: parameters["rowFilter.elrh_article.name"];
          dscr?: parameters["rowFilter.elrh_article.dscr"];
          content?: parameters["rowFilter.elrh_article.content"];
          thumb?: parameters["rowFilter.elrh_article.thumb"];
          authorId?: parameters["rowFilter.elrh_article.authorId"];
          galleryId?: parameters["rowFilter.elrh_article.galleryId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_article"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_article */
          elrh_article?: definitions["elrh_article"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrh_article.articleId"];
          categoryId?: parameters["rowFilter.elrh_article.categoryId"];
          dateCreated?: parameters["rowFilter.elrh_article.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_article.dateEdited"];
          name?: parameters["rowFilter.elrh_article.name"];
          dscr?: parameters["rowFilter.elrh_article.dscr"];
          content?: parameters["rowFilter.elrh_article.content"];
          thumb?: parameters["rowFilter.elrh_article.thumb"];
          authorId?: parameters["rowFilter.elrh_article.authorId"];
          galleryId?: parameters["rowFilter.elrh_article.galleryId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrh_article.articleId"];
          categoryId?: parameters["rowFilter.elrh_article.categoryId"];
          dateCreated?: parameters["rowFilter.elrh_article.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_article.dateEdited"];
          name?: parameters["rowFilter.elrh_article.name"];
          dscr?: parameters["rowFilter.elrh_article.dscr"];
          content?: parameters["rowFilter.elrh_article.content"];
          thumb?: parameters["rowFilter.elrh_article.thumb"];
          authorId?: parameters["rowFilter.elrh_article.authorId"];
          galleryId?: parameters["rowFilter.elrh_article.galleryId"];
        };
        body: {
          /** elrh_article */
          elrh_article?: definitions["elrh_article"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_contact": {
    get: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrh_contact.contactId"];
          name?: parameters["rowFilter.elrh_contact.name"];
          email?: parameters["rowFilter.elrh_contact.email"];
          phone?: parameters["rowFilter.elrh_contact.phone"];
          fb?: parameters["rowFilter.elrh_contact.fb"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_contact"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_contact */
          elrh_contact?: definitions["elrh_contact"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrh_contact.contactId"];
          name?: parameters["rowFilter.elrh_contact.name"];
          email?: parameters["rowFilter.elrh_contact.email"];
          phone?: parameters["rowFilter.elrh_contact.phone"];
          fb?: parameters["rowFilter.elrh_contact.fb"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          contactId?: parameters["rowFilter.elrh_contact.contactId"];
          name?: parameters["rowFilter.elrh_contact.name"];
          email?: parameters["rowFilter.elrh_contact.email"];
          phone?: parameters["rowFilter.elrh_contact.phone"];
          fb?: parameters["rowFilter.elrh_contact.fb"];
        };
        body: {
          /** elrh_contact */
          elrh_contact?: definitions["elrh_contact"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_gallery": {
    get: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrh_gallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrh_gallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_gallery.dateEdited"];
          name?: parameters["rowFilter.elrh_gallery.name"];
          dscr?: parameters["rowFilter.elrh_gallery.dscr"];
          authorId?: parameters["rowFilter.elrh_gallery.authorId"];
          parentId?: parameters["rowFilter.elrh_gallery.parentId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_gallery"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_gallery */
          elrh_gallery?: definitions["elrh_gallery"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrh_gallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrh_gallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_gallery.dateEdited"];
          name?: parameters["rowFilter.elrh_gallery.name"];
          dscr?: parameters["rowFilter.elrh_gallery.dscr"];
          authorId?: parameters["rowFilter.elrh_gallery.authorId"];
          parentId?: parameters["rowFilter.elrh_gallery.parentId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrh_gallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrh_gallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_gallery.dateEdited"];
          name?: parameters["rowFilter.elrh_gallery.name"];
          dscr?: parameters["rowFilter.elrh_gallery.dscr"];
          authorId?: parameters["rowFilter.elrh_gallery.authorId"];
          parentId?: parameters["rowFilter.elrh_gallery.parentId"];
        };
        body: {
          /** elrh_gallery */
          elrh_gallery?: definitions["elrh_gallery"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhCategory": {
    get: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrhCategory.categoryId"];
          ord?: parameters["rowFilter.elrhCategory.ord"];
          name?: parameters["rowFilter.elrhCategory.name"];
          dscr?: parameters["rowFilter.elrhCategory.dscr"];
          type?: parameters["rowFilter.elrhCategory.type"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhCategory"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhCategory */
          elrhCategory?: definitions["elrhCategory"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrhCategory.categoryId"];
          ord?: parameters["rowFilter.elrhCategory.ord"];
          name?: parameters["rowFilter.elrhCategory.name"];
          dscr?: parameters["rowFilter.elrhCategory.dscr"];
          type?: parameters["rowFilter.elrhCategory.type"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrhCategory.categoryId"];
          ord?: parameters["rowFilter.elrhCategory.ord"];
          name?: parameters["rowFilter.elrhCategory.name"];
          dscr?: parameters["rowFilter.elrhCategory.dscr"];
          type?: parameters["rowFilter.elrhCategory.type"];
        };
        body: {
          /** elrhCategory */
          elrhCategory?: definitions["elrhCategory"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhNews": {
    get: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrhNews.newsId"];
          content?: parameters["rowFilter.elrhNews.content"];
          authorId?: parameters["rowFilter.elrhNews.authorId"];
          dateCreated?: parameters["rowFilter.elrhNews.dateCreated"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhNews"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhNews */
          elrhNews?: definitions["elrhNews"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrhNews.newsId"];
          content?: parameters["rowFilter.elrhNews.content"];
          authorId?: parameters["rowFilter.elrhNews.authorId"];
          dateCreated?: parameters["rowFilter.elrhNews.dateCreated"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrhNews.newsId"];
          content?: parameters["rowFilter.elrhNews.content"];
          authorId?: parameters["rowFilter.elrhNews.authorId"];
          dateCreated?: parameters["rowFilter.elrhNews.dateCreated"];
        };
        body: {
          /** elrhNews */
          elrhNews?: definitions["elrhNews"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_author": {
    get: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrh_author.authorId"];
          email?: parameters["rowFilter.elrh_author.email"];
          name?: parameters["rowFilter.elrh_author.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_author"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_author */
          elrh_author?: definitions["elrh_author"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrh_author.authorId"];
          email?: parameters["rowFilter.elrh_author.email"];
          name?: parameters["rowFilter.elrh_author.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrh_author.authorId"];
          email?: parameters["rowFilter.elrh_author.email"];
          name?: parameters["rowFilter.elrh_author.name"];
        };
        body: {
          /** elrh_author */
          elrh_author?: definitions["elrh_author"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_link": {
    get: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrh_link.linkId"];
          categoryId?: parameters["rowFilter.elrh_link.categoryId"];
          ord?: parameters["rowFilter.elrh_link.ord"];
          dateCreated?: parameters["rowFilter.elrh_link.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_link.dateEdited"];
          name?: parameters["rowFilter.elrh_link.name"];
          dscr?: parameters["rowFilter.elrh_link.dscr"];
          url?: parameters["rowFilter.elrh_link.url"];
          thumb?: parameters["rowFilter.elrh_link.thumb"];
          authorId?: parameters["rowFilter.elrh_link.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_link"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_link */
          elrh_link?: definitions["elrh_link"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrh_link.linkId"];
          categoryId?: parameters["rowFilter.elrh_link.categoryId"];
          ord?: parameters["rowFilter.elrh_link.ord"];
          dateCreated?: parameters["rowFilter.elrh_link.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_link.dateEdited"];
          name?: parameters["rowFilter.elrh_link.name"];
          dscr?: parameters["rowFilter.elrh_link.dscr"];
          url?: parameters["rowFilter.elrh_link.url"];
          thumb?: parameters["rowFilter.elrh_link.thumb"];
          authorId?: parameters["rowFilter.elrh_link.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrh_link.linkId"];
          categoryId?: parameters["rowFilter.elrh_link.categoryId"];
          ord?: parameters["rowFilter.elrh_link.ord"];
          dateCreated?: parameters["rowFilter.elrh_link.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_link.dateEdited"];
          name?: parameters["rowFilter.elrh_link.name"];
          dscr?: parameters["rowFilter.elrh_link.dscr"];
          url?: parameters["rowFilter.elrh_link.url"];
          thumb?: parameters["rowFilter.elrh_link.thumb"];
          authorId?: parameters["rowFilter.elrh_link.authorId"];
        };
        body: {
          /** elrh_link */
          elrh_link?: definitions["elrh_link"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhText": {
    get: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrhText.key"];
          value?: parameters["rowFilter.elrhText.value"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhText"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhText */
          elrhText?: definitions["elrhText"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrhText.key"];
          value?: parameters["rowFilter.elrhText.value"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrhText.key"];
          value?: parameters["rowFilter.elrhText.value"];
        };
        body: {
          /** elrhText */
          elrhText?: definitions["elrhText"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhGallery": {
    get: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrhGallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrhGallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhGallery.dateEdited"];
          name?: parameters["rowFilter.elrhGallery.name"];
          dscr?: parameters["rowFilter.elrhGallery.dscr"];
          authorId?: parameters["rowFilter.elrhGallery.authorId"];
          parentId?: parameters["rowFilter.elrhGallery.parentId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhGallery"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhGallery */
          elrhGallery?: definitions["elrhGallery"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrhGallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrhGallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhGallery.dateEdited"];
          name?: parameters["rowFilter.elrhGallery.name"];
          dscr?: parameters["rowFilter.elrhGallery.dscr"];
          authorId?: parameters["rowFilter.elrhGallery.authorId"];
          parentId?: parameters["rowFilter.elrhGallery.parentId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          galleryId?: parameters["rowFilter.elrhGallery.galleryId"];
          dateCreated?: parameters["rowFilter.elrhGallery.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhGallery.dateEdited"];
          name?: parameters["rowFilter.elrhGallery.name"];
          dscr?: parameters["rowFilter.elrhGallery.dscr"];
          authorId?: parameters["rowFilter.elrhGallery.authorId"];
          parentId?: parameters["rowFilter.elrhGallery.parentId"];
        };
        body: {
          /** elrhGallery */
          elrhGallery?: definitions["elrhGallery"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_image": {
    get: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrh_image.imageId"];
          dateCreated?: parameters["rowFilter.elrh_image.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_image.dateEdited"];
          name?: parameters["rowFilter.elrh_image.name"];
          dscr?: parameters["rowFilter.elrh_image.dscr"];
          authorId?: parameters["rowFilter.elrh_image.authorId"];
          image?: parameters["rowFilter.elrh_image.image"];
          galleryId?: parameters["rowFilter.elrh_image.galleryId"];
          ord?: parameters["rowFilter.elrh_image.ord"];
          prevId?: parameters["rowFilter.elrh_image.prevId"];
          nextId?: parameters["rowFilter.elrh_image.nextId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_image"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_image */
          elrh_image?: definitions["elrh_image"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrh_image.imageId"];
          dateCreated?: parameters["rowFilter.elrh_image.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_image.dateEdited"];
          name?: parameters["rowFilter.elrh_image.name"];
          dscr?: parameters["rowFilter.elrh_image.dscr"];
          authorId?: parameters["rowFilter.elrh_image.authorId"];
          image?: parameters["rowFilter.elrh_image.image"];
          galleryId?: parameters["rowFilter.elrh_image.galleryId"];
          ord?: parameters["rowFilter.elrh_image.ord"];
          prevId?: parameters["rowFilter.elrh_image.prevId"];
          nextId?: parameters["rowFilter.elrh_image.nextId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrh_image.imageId"];
          dateCreated?: parameters["rowFilter.elrh_image.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_image.dateEdited"];
          name?: parameters["rowFilter.elrh_image.name"];
          dscr?: parameters["rowFilter.elrh_image.dscr"];
          authorId?: parameters["rowFilter.elrh_image.authorId"];
          image?: parameters["rowFilter.elrh_image.image"];
          galleryId?: parameters["rowFilter.elrh_image.galleryId"];
          ord?: parameters["rowFilter.elrh_image.ord"];
          prevId?: parameters["rowFilter.elrh_image.prevId"];
          nextId?: parameters["rowFilter.elrh_image.nextId"];
        };
        body: {
          /** elrh_image */
          elrh_image?: definitions["elrh_image"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhBook": {
    get: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrhBook.bookId"];
          categoryId?: parameters["rowFilter.elrhBook.categoryId"];
          ord?: parameters["rowFilter.elrhBook.ord"];
          dateCreated?: parameters["rowFilter.elrhBook.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhBook.dateEdited"];
          writer?: parameters["rowFilter.elrhBook.writer"];
          name?: parameters["rowFilter.elrhBook.name"];
          dscr?: parameters["rowFilter.elrhBook.dscr"];
          url?: parameters["rowFilter.elrhBook.url"];
          thumb?: parameters["rowFilter.elrhBook.thumb"];
          review?: parameters["rowFilter.elrhBook.review"];
          year?: parameters["rowFilter.elrhBook.year"];
          authorId?: parameters["rowFilter.elrhBook.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhBook"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhBook */
          elrhBook?: definitions["elrhBook"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrhBook.bookId"];
          categoryId?: parameters["rowFilter.elrhBook.categoryId"];
          ord?: parameters["rowFilter.elrhBook.ord"];
          dateCreated?: parameters["rowFilter.elrhBook.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhBook.dateEdited"];
          writer?: parameters["rowFilter.elrhBook.writer"];
          name?: parameters["rowFilter.elrhBook.name"];
          dscr?: parameters["rowFilter.elrhBook.dscr"];
          url?: parameters["rowFilter.elrhBook.url"];
          thumb?: parameters["rowFilter.elrhBook.thumb"];
          review?: parameters["rowFilter.elrhBook.review"];
          year?: parameters["rowFilter.elrhBook.year"];
          authorId?: parameters["rowFilter.elrhBook.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrhBook.bookId"];
          categoryId?: parameters["rowFilter.elrhBook.categoryId"];
          ord?: parameters["rowFilter.elrhBook.ord"];
          dateCreated?: parameters["rowFilter.elrhBook.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhBook.dateEdited"];
          writer?: parameters["rowFilter.elrhBook.writer"];
          name?: parameters["rowFilter.elrhBook.name"];
          dscr?: parameters["rowFilter.elrhBook.dscr"];
          url?: parameters["rowFilter.elrhBook.url"];
          thumb?: parameters["rowFilter.elrhBook.thumb"];
          review?: parameters["rowFilter.elrhBook.review"];
          year?: parameters["rowFilter.elrhBook.year"];
          authorId?: parameters["rowFilter.elrhBook.authorId"];
        };
        body: {
          /** elrhBook */
          elrhBook?: definitions["elrhBook"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhArticle": {
    get: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrhArticle.articleId"];
          categoryId?: parameters["rowFilter.elrhArticle.categoryId"];
          dateCreated?: parameters["rowFilter.elrhArticle.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhArticle.dateEdited"];
          name?: parameters["rowFilter.elrhArticle.name"];
          dscr?: parameters["rowFilter.elrhArticle.dscr"];
          content?: parameters["rowFilter.elrhArticle.content"];
          thumb?: parameters["rowFilter.elrhArticle.thumb"];
          authorId?: parameters["rowFilter.elrhArticle.authorId"];
          galleryId?: parameters["rowFilter.elrhArticle.galleryId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhArticle"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhArticle */
          elrhArticle?: definitions["elrhArticle"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrhArticle.articleId"];
          categoryId?: parameters["rowFilter.elrhArticle.categoryId"];
          dateCreated?: parameters["rowFilter.elrhArticle.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhArticle.dateEdited"];
          name?: parameters["rowFilter.elrhArticle.name"];
          dscr?: parameters["rowFilter.elrhArticle.dscr"];
          content?: parameters["rowFilter.elrhArticle.content"];
          thumb?: parameters["rowFilter.elrhArticle.thumb"];
          authorId?: parameters["rowFilter.elrhArticle.authorId"];
          galleryId?: parameters["rowFilter.elrhArticle.galleryId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          articleId?: parameters["rowFilter.elrhArticle.articleId"];
          categoryId?: parameters["rowFilter.elrhArticle.categoryId"];
          dateCreated?: parameters["rowFilter.elrhArticle.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhArticle.dateEdited"];
          name?: parameters["rowFilter.elrhArticle.name"];
          dscr?: parameters["rowFilter.elrhArticle.dscr"];
          content?: parameters["rowFilter.elrhArticle.content"];
          thumb?: parameters["rowFilter.elrhArticle.thumb"];
          authorId?: parameters["rowFilter.elrhArticle.authorId"];
          galleryId?: parameters["rowFilter.elrhArticle.galleryId"];
        };
        body: {
          /** elrhArticle */
          elrhArticle?: definitions["elrhArticle"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_news": {
    get: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrh_news.newsId"];
          content?: parameters["rowFilter.elrh_news.content"];
          authorId?: parameters["rowFilter.elrh_news.authorId"];
          dateCreated?: parameters["rowFilter.elrh_news.dateCreated"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_news"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_news */
          elrh_news?: definitions["elrh_news"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrh_news.newsId"];
          content?: parameters["rowFilter.elrh_news.content"];
          authorId?: parameters["rowFilter.elrh_news.authorId"];
          dateCreated?: parameters["rowFilter.elrh_news.dateCreated"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          newsId?: parameters["rowFilter.elrh_news.newsId"];
          content?: parameters["rowFilter.elrh_news.content"];
          authorId?: parameters["rowFilter.elrh_news.authorId"];
          dateCreated?: parameters["rowFilter.elrh_news.dateCreated"];
        };
        body: {
          /** elrh_news */
          elrh_news?: definitions["elrh_news"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhImage": {
    get: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrhImage.imageId"];
          dateCreated?: parameters["rowFilter.elrhImage.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhImage.dateEdited"];
          name?: parameters["rowFilter.elrhImage.name"];
          dscr?: parameters["rowFilter.elrhImage.dscr"];
          authorId?: parameters["rowFilter.elrhImage.authorId"];
          image?: parameters["rowFilter.elrhImage.image"];
          galleryId?: parameters["rowFilter.elrhImage.galleryId"];
          ord?: parameters["rowFilter.elrhImage.ord"];
          prevId?: parameters["rowFilter.elrhImage.prevId"];
          nextId?: parameters["rowFilter.elrhImage.nextId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhImage"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhImage */
          elrhImage?: definitions["elrhImage"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrhImage.imageId"];
          dateCreated?: parameters["rowFilter.elrhImage.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhImage.dateEdited"];
          name?: parameters["rowFilter.elrhImage.name"];
          dscr?: parameters["rowFilter.elrhImage.dscr"];
          authorId?: parameters["rowFilter.elrhImage.authorId"];
          image?: parameters["rowFilter.elrhImage.image"];
          galleryId?: parameters["rowFilter.elrhImage.galleryId"];
          ord?: parameters["rowFilter.elrhImage.ord"];
          prevId?: parameters["rowFilter.elrhImage.prevId"];
          nextId?: parameters["rowFilter.elrhImage.nextId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          imageId?: parameters["rowFilter.elrhImage.imageId"];
          dateCreated?: parameters["rowFilter.elrhImage.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhImage.dateEdited"];
          name?: parameters["rowFilter.elrhImage.name"];
          dscr?: parameters["rowFilter.elrhImage.dscr"];
          authorId?: parameters["rowFilter.elrhImage.authorId"];
          image?: parameters["rowFilter.elrhImage.image"];
          galleryId?: parameters["rowFilter.elrhImage.galleryId"];
          ord?: parameters["rowFilter.elrhImage.ord"];
          prevId?: parameters["rowFilter.elrhImage.prevId"];
          nextId?: parameters["rowFilter.elrhImage.nextId"];
        };
        body: {
          /** elrhImage */
          elrhImage?: definitions["elrhImage"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhLink": {
    get: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrhLink.linkId"];
          categoryId?: parameters["rowFilter.elrhLink.categoryId"];
          ord?: parameters["rowFilter.elrhLink.ord"];
          dateCreated?: parameters["rowFilter.elrhLink.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhLink.dateEdited"];
          name?: parameters["rowFilter.elrhLink.name"];
          dscr?: parameters["rowFilter.elrhLink.dscr"];
          url?: parameters["rowFilter.elrhLink.url"];
          thumb?: parameters["rowFilter.elrhLink.thumb"];
          authorId?: parameters["rowFilter.elrhLink.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhLink"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhLink */
          elrhLink?: definitions["elrhLink"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrhLink.linkId"];
          categoryId?: parameters["rowFilter.elrhLink.categoryId"];
          ord?: parameters["rowFilter.elrhLink.ord"];
          dateCreated?: parameters["rowFilter.elrhLink.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhLink.dateEdited"];
          name?: parameters["rowFilter.elrhLink.name"];
          dscr?: parameters["rowFilter.elrhLink.dscr"];
          url?: parameters["rowFilter.elrhLink.url"];
          thumb?: parameters["rowFilter.elrhLink.thumb"];
          authorId?: parameters["rowFilter.elrhLink.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          linkId?: parameters["rowFilter.elrhLink.linkId"];
          categoryId?: parameters["rowFilter.elrhLink.categoryId"];
          ord?: parameters["rowFilter.elrhLink.ord"];
          dateCreated?: parameters["rowFilter.elrhLink.dateCreated"];
          dateEdited?: parameters["rowFilter.elrhLink.dateEdited"];
          name?: parameters["rowFilter.elrhLink.name"];
          dscr?: parameters["rowFilter.elrhLink.dscr"];
          url?: parameters["rowFilter.elrhLink.url"];
          thumb?: parameters["rowFilter.elrhLink.thumb"];
          authorId?: parameters["rowFilter.elrhLink.authorId"];
        };
        body: {
          /** elrhLink */
          elrhLink?: definitions["elrhLink"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_text": {
    get: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrh_text.key"];
          value?: parameters["rowFilter.elrh_text.value"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_text"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_text */
          elrh_text?: definitions["elrh_text"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrh_text.key"];
          value?: parameters["rowFilter.elrh_text.value"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          key?: parameters["rowFilter.elrh_text.key"];
          value?: parameters["rowFilter.elrh_text.value"];
        };
        body: {
          /** elrh_text */
          elrh_text?: definitions["elrh_text"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrhAuthor": {
    get: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrhAuthor.authorId"];
          email?: parameters["rowFilter.elrhAuthor.email"];
          name?: parameters["rowFilter.elrhAuthor.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrhAuthor"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrhAuthor */
          elrhAuthor?: definitions["elrhAuthor"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrhAuthor.authorId"];
          email?: parameters["rowFilter.elrhAuthor.email"];
          name?: parameters["rowFilter.elrhAuthor.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          authorId?: parameters["rowFilter.elrhAuthor.authorId"];
          email?: parameters["rowFilter.elrhAuthor.email"];
          name?: parameters["rowFilter.elrhAuthor.name"];
        };
        body: {
          /** elrhAuthor */
          elrhAuthor?: definitions["elrhAuthor"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_category": {
    get: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrh_category.categoryId"];
          ord?: parameters["rowFilter.elrh_category.ord"];
          name?: parameters["rowFilter.elrh_category.name"];
          dscr?: parameters["rowFilter.elrh_category.dscr"];
          type?: parameters["rowFilter.elrh_category.type"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_category"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_category */
          elrh_category?: definitions["elrh_category"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrh_category.categoryId"];
          ord?: parameters["rowFilter.elrh_category.ord"];
          name?: parameters["rowFilter.elrh_category.name"];
          dscr?: parameters["rowFilter.elrh_category.dscr"];
          type?: parameters["rowFilter.elrh_category.type"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          categoryId?: parameters["rowFilter.elrh_category.categoryId"];
          ord?: parameters["rowFilter.elrh_category.ord"];
          name?: parameters["rowFilter.elrh_category.name"];
          dscr?: parameters["rowFilter.elrh_category.dscr"];
          type?: parameters["rowFilter.elrh_category.type"];
        };
        body: {
          /** elrh_category */
          elrh_category?: definitions["elrh_category"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/elrh_book": {
    get: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrh_book.bookId"];
          categoryId?: parameters["rowFilter.elrh_book.categoryId"];
          ord?: parameters["rowFilter.elrh_book.ord"];
          dateCreated?: parameters["rowFilter.elrh_book.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_book.dateEdited"];
          writer?: parameters["rowFilter.elrh_book.writer"];
          name?: parameters["rowFilter.elrh_book.name"];
          dscr?: parameters["rowFilter.elrh_book.dscr"];
          url?: parameters["rowFilter.elrh_book.url"];
          thumb?: parameters["rowFilter.elrh_book.thumb"];
          review?: parameters["rowFilter.elrh_book.review"];
          year?: parameters["rowFilter.elrh_book.year"];
          authorId?: parameters["rowFilter.elrh_book.authorId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["elrh_book"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** elrh_book */
          elrh_book?: definitions["elrh_book"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrh_book.bookId"];
          categoryId?: parameters["rowFilter.elrh_book.categoryId"];
          ord?: parameters["rowFilter.elrh_book.ord"];
          dateCreated?: parameters["rowFilter.elrh_book.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_book.dateEdited"];
          writer?: parameters["rowFilter.elrh_book.writer"];
          name?: parameters["rowFilter.elrh_book.name"];
          dscr?: parameters["rowFilter.elrh_book.dscr"];
          url?: parameters["rowFilter.elrh_book.url"];
          thumb?: parameters["rowFilter.elrh_book.thumb"];
          review?: parameters["rowFilter.elrh_book.review"];
          year?: parameters["rowFilter.elrh_book.year"];
          authorId?: parameters["rowFilter.elrh_book.authorId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          bookId?: parameters["rowFilter.elrh_book.bookId"];
          categoryId?: parameters["rowFilter.elrh_book.categoryId"];
          ord?: parameters["rowFilter.elrh_book.ord"];
          dateCreated?: parameters["rowFilter.elrh_book.dateCreated"];
          dateEdited?: parameters["rowFilter.elrh_book.dateEdited"];
          writer?: parameters["rowFilter.elrh_book.writer"];
          name?: parameters["rowFilter.elrh_book.name"];
          dscr?: parameters["rowFilter.elrh_book.dscr"];
          url?: parameters["rowFilter.elrh_book.url"];
          thumb?: parameters["rowFilter.elrh_book.thumb"];
          review?: parameters["rowFilter.elrh_book.review"];
          year?: parameters["rowFilter.elrh_book.year"];
          authorId?: parameters["rowFilter.elrh_book.authorId"];
        };
        body: {
          /** elrh_book */
          elrh_book?: definitions["elrh_book"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  elrhContact: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    contactId: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    phone: string;
    /** Format: character varying */
    fb: string;
  };
  elrh_article: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    articleId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_category.categoryId`.<fk table='elrh_category' column='categoryId'/>
     */
    categoryId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: text */
    content: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.authorId`.<fk table='elrh_author' column='authorId'/>
     */
    authorId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_gallery.galleryId`.<fk table='elrh_gallery' column='galleryId'/>
     */
    galleryId?: number;
  };
  elrh_contact: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    contactId: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    phone: string;
    /** Format: character varying */
    fb: string;
  };
  elrh_gallery: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    galleryId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.authorId`.<fk table='elrh_author' column='authorId'/>
     */
    authorId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_gallery.galleryId`.<fk table='elrh_gallery' column='galleryId'/>
     */
    parentId?: number;
  };
  elrhCategory: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    type: string;
  };
  elrhNews: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    newsId: number;
    /** Format: text */
    content: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
  };
  elrh_author: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    authorId: number;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    name: string;
  };
  elrh_link: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    linkId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_category.categoryId`.<fk table='elrh_category' column='categoryId'/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.authorId`.<fk table='elrh_author' column='authorId'/>
     */
    authorId: number;
  };
  elrhText: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    key: string;
    /** Format: text */
    value: string;
  };
  elrhGallery: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    galleryId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhGallery.galleryId`.<fk table='elrhGallery' column='galleryId'/>
     */
    parentId?: number;
  };
  elrh_image: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    imageId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.authorId`.<fk table='elrh_author' column='authorId'/>
     */
    authorId: number;
    /** Format: character varying */
    image: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_gallery.galleryId`.<fk table='elrh_gallery' column='galleryId'/>
     */
    galleryId: number;
    /** Format: integer */
    ord: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_image.imageId`.<fk table='elrh_image' column='imageId'/>
     */
    prevId?: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_image.imageId`.<fk table='elrh_image' column='imageId'/>
     */
    nextId?: number;
  };
  elrhBook: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    bookId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhCategory.categoryId`.<fk table='elrhCategory' column='categoryId'/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    writer: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /** Format: character varying */
    review?: string;
    /** Format: character varying */
    year: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
  };
  elrhArticle: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    articleId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhCategory.categoryId`.<fk table='elrhCategory' column='categoryId'/>
     */
    categoryId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: text */
    content: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhGallery.galleryId`.<fk table='elrhGallery' column='galleryId'/>
     */
    galleryId?: number;
  };
  elrh_news: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    newsId: number;
    /** Format: text */
    content: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.authorId`.<fk table='elrh_author' column='authorId'/>
     */
    authorId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
  };
  elrhImage: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    imageId: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    dscr?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
    /** Format: character varying */
    image: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhGallery.galleryId`.<fk table='elrhGallery' column='galleryId'/>
     */
    galleryId: number;
    /** Format: integer */
    ord: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhImage.imageId`.<fk table='elrhImage' column='imageId'/>
     */
    prevId?: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhImage.imageId`.<fk table='elrhImage' column='imageId'/>
     */
    nextId?: number;
  };
  elrhLink: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    linkId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhCategory.categoryId`.<fk table='elrhCategory' column='categoryId'/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrhAuthor.authorId`.<fk table='elrhAuthor' column='authorId'/>
     */
    authorId: number;
  };
  elrh_text: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    key: string;
    /** Format: text */
    value: string;
  };
  elrhAuthor: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    authorId: number;
    /** Format: character varying */
    email: string;
    /** Format: character varying */
    name: string;
  };
  elrh_category: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    type: string;
  };
  elrh_book: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    bookId: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_category.categoryId`.<fk table='elrh_category' column='categoryId'/>
     */
    categoryId: number;
    /** Format: integer */
    ord: number;
    /** Format: timestamp without time zone */
    dateCreated: string;
    /** Format: timestamp without time zone */
    dateEdited: string;
    /** Format: character varying */
    writer: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    dscr: string;
    /** Format: character varying */
    url: string;
    /** Format: character varying */
    thumb: string;
    /** Format: character varying */
    review?: string;
    /** Format: character varying */
    year: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `elrh_author.authorId`.<fk table='elrh_author' column='authorId'/>
     */
    authorId: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description elrhContact */
  "body.elrhContact": definitions["elrhContact"];
  /** Format: integer */
  "rowFilter.elrhContact.contactId": string;
  /** Format: character varying */
  "rowFilter.elrhContact.name": string;
  /** Format: character varying */
  "rowFilter.elrhContact.email": string;
  /** Format: character varying */
  "rowFilter.elrhContact.phone": string;
  /** Format: character varying */
  "rowFilter.elrhContact.fb": string;
  /** @description elrh_article */
  "body.elrh_article": definitions["elrh_article"];
  /** Format: integer */
  "rowFilter.elrh_article.articleId": string;
  /** Format: integer */
  "rowFilter.elrh_article.categoryId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_article.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_article.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrh_article.name": string;
  /** Format: character varying */
  "rowFilter.elrh_article.dscr": string;
  /** Format: text */
  "rowFilter.elrh_article.content": string;
  /** Format: character varying */
  "rowFilter.elrh_article.thumb": string;
  /** Format: integer */
  "rowFilter.elrh_article.authorId": string;
  /** Format: integer */
  "rowFilter.elrh_article.galleryId": string;
  /** @description elrh_contact */
  "body.elrh_contact": definitions["elrh_contact"];
  /** Format: integer */
  "rowFilter.elrh_contact.contactId": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.name": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.email": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.phone": string;
  /** Format: character varying */
  "rowFilter.elrh_contact.fb": string;
  /** @description elrh_gallery */
  "body.elrh_gallery": definitions["elrh_gallery"];
  /** Format: integer */
  "rowFilter.elrh_gallery.galleryId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_gallery.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_gallery.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrh_gallery.name": string;
  /** Format: text */
  "rowFilter.elrh_gallery.dscr": string;
  /** Format: integer */
  "rowFilter.elrh_gallery.authorId": string;
  /** Format: integer */
  "rowFilter.elrh_gallery.parentId": string;
  /** @description elrhCategory */
  "body.elrhCategory": definitions["elrhCategory"];
  /** Format: integer */
  "rowFilter.elrhCategory.categoryId": string;
  /** Format: integer */
  "rowFilter.elrhCategory.ord": string;
  /** Format: character varying */
  "rowFilter.elrhCategory.name": string;
  /** Format: character varying */
  "rowFilter.elrhCategory.dscr": string;
  /** Format: character varying */
  "rowFilter.elrhCategory.type": string;
  /** @description elrhNews */
  "body.elrhNews": definitions["elrhNews"];
  /** Format: integer */
  "rowFilter.elrhNews.newsId": string;
  /** Format: text */
  "rowFilter.elrhNews.content": string;
  /** Format: integer */
  "rowFilter.elrhNews.authorId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhNews.dateCreated": string;
  /** @description elrh_author */
  "body.elrh_author": definitions["elrh_author"];
  /** Format: integer */
  "rowFilter.elrh_author.authorId": string;
  /** Format: character varying */
  "rowFilter.elrh_author.email": string;
  /** Format: character varying */
  "rowFilter.elrh_author.name": string;
  /** @description elrh_link */
  "body.elrh_link": definitions["elrh_link"];
  /** Format: integer */
  "rowFilter.elrh_link.linkId": string;
  /** Format: integer */
  "rowFilter.elrh_link.categoryId": string;
  /** Format: integer */
  "rowFilter.elrh_link.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_link.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_link.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrh_link.name": string;
  /** Format: character varying */
  "rowFilter.elrh_link.dscr": string;
  /** Format: character varying */
  "rowFilter.elrh_link.url": string;
  /** Format: character varying */
  "rowFilter.elrh_link.thumb": string;
  /** Format: integer */
  "rowFilter.elrh_link.authorId": string;
  /** @description elrhText */
  "body.elrhText": definitions["elrhText"];
  /** Format: text */
  "rowFilter.elrhText.key": string;
  /** Format: text */
  "rowFilter.elrhText.value": string;
  /** @description elrhGallery */
  "body.elrhGallery": definitions["elrhGallery"];
  /** Format: integer */
  "rowFilter.elrhGallery.galleryId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhGallery.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhGallery.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhGallery.name": string;
  /** Format: text */
  "rowFilter.elrhGallery.dscr": string;
  /** Format: integer */
  "rowFilter.elrhGallery.authorId": string;
  /** Format: integer */
  "rowFilter.elrhGallery.parentId": string;
  /** @description elrh_image */
  "body.elrh_image": definitions["elrh_image"];
  /** Format: integer */
  "rowFilter.elrh_image.imageId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_image.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_image.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrh_image.name": string;
  /** Format: text */
  "rowFilter.elrh_image.dscr": string;
  /** Format: integer */
  "rowFilter.elrh_image.authorId": string;
  /** Format: character varying */
  "rowFilter.elrh_image.image": string;
  /** Format: integer */
  "rowFilter.elrh_image.galleryId": string;
  /** Format: integer */
  "rowFilter.elrh_image.ord": string;
  /** Format: integer */
  "rowFilter.elrh_image.prevId": string;
  /** Format: integer */
  "rowFilter.elrh_image.nextId": string;
  /** @description elrhBook */
  "body.elrhBook": definitions["elrhBook"];
  /** Format: integer */
  "rowFilter.elrhBook.bookId": string;
  /** Format: integer */
  "rowFilter.elrhBook.categoryId": string;
  /** Format: integer */
  "rowFilter.elrhBook.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhBook.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhBook.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhBook.writer": string;
  /** Format: character varying */
  "rowFilter.elrhBook.name": string;
  /** Format: character varying */
  "rowFilter.elrhBook.dscr": string;
  /** Format: character varying */
  "rowFilter.elrhBook.url": string;
  /** Format: character varying */
  "rowFilter.elrhBook.thumb": string;
  /** Format: character varying */
  "rowFilter.elrhBook.review": string;
  /** Format: character varying */
  "rowFilter.elrhBook.year": string;
  /** Format: integer */
  "rowFilter.elrhBook.authorId": string;
  /** @description elrhArticle */
  "body.elrhArticle": definitions["elrhArticle"];
  /** Format: integer */
  "rowFilter.elrhArticle.articleId": string;
  /** Format: integer */
  "rowFilter.elrhArticle.categoryId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhArticle.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhArticle.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhArticle.name": string;
  /** Format: character varying */
  "rowFilter.elrhArticle.dscr": string;
  /** Format: text */
  "rowFilter.elrhArticle.content": string;
  /** Format: character varying */
  "rowFilter.elrhArticle.thumb": string;
  /** Format: integer */
  "rowFilter.elrhArticle.authorId": string;
  /** Format: integer */
  "rowFilter.elrhArticle.galleryId": string;
  /** @description elrh_news */
  "body.elrh_news": definitions["elrh_news"];
  /** Format: integer */
  "rowFilter.elrh_news.newsId": string;
  /** Format: text */
  "rowFilter.elrh_news.content": string;
  /** Format: integer */
  "rowFilter.elrh_news.authorId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_news.dateCreated": string;
  /** @description elrhImage */
  "body.elrhImage": definitions["elrhImage"];
  /** Format: integer */
  "rowFilter.elrhImage.imageId": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhImage.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhImage.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhImage.name": string;
  /** Format: text */
  "rowFilter.elrhImage.dscr": string;
  /** Format: integer */
  "rowFilter.elrhImage.authorId": string;
  /** Format: character varying */
  "rowFilter.elrhImage.image": string;
  /** Format: integer */
  "rowFilter.elrhImage.galleryId": string;
  /** Format: integer */
  "rowFilter.elrhImage.ord": string;
  /** Format: integer */
  "rowFilter.elrhImage.prevId": string;
  /** Format: integer */
  "rowFilter.elrhImage.nextId": string;
  /** @description elrhLink */
  "body.elrhLink": definitions["elrhLink"];
  /** Format: integer */
  "rowFilter.elrhLink.linkId": string;
  /** Format: integer */
  "rowFilter.elrhLink.categoryId": string;
  /** Format: integer */
  "rowFilter.elrhLink.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhLink.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrhLink.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrhLink.name": string;
  /** Format: character varying */
  "rowFilter.elrhLink.dscr": string;
  /** Format: character varying */
  "rowFilter.elrhLink.url": string;
  /** Format: character varying */
  "rowFilter.elrhLink.thumb": string;
  /** Format: integer */
  "rowFilter.elrhLink.authorId": string;
  /** @description elrh_text */
  "body.elrh_text": definitions["elrh_text"];
  /** Format: text */
  "rowFilter.elrh_text.key": string;
  /** Format: text */
  "rowFilter.elrh_text.value": string;
  /** @description elrhAuthor */
  "body.elrhAuthor": definitions["elrhAuthor"];
  /** Format: integer */
  "rowFilter.elrhAuthor.authorId": string;
  /** Format: character varying */
  "rowFilter.elrhAuthor.email": string;
  /** Format: character varying */
  "rowFilter.elrhAuthor.name": string;
  /** @description elrh_category */
  "body.elrh_category": definitions["elrh_category"];
  /** Format: integer */
  "rowFilter.elrh_category.categoryId": string;
  /** Format: integer */
  "rowFilter.elrh_category.ord": string;
  /** Format: character varying */
  "rowFilter.elrh_category.name": string;
  /** Format: character varying */
  "rowFilter.elrh_category.dscr": string;
  /** Format: character varying */
  "rowFilter.elrh_category.type": string;
  /** @description elrh_book */
  "body.elrh_book": definitions["elrh_book"];
  /** Format: integer */
  "rowFilter.elrh_book.bookId": string;
  /** Format: integer */
  "rowFilter.elrh_book.categoryId": string;
  /** Format: integer */
  "rowFilter.elrh_book.ord": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_book.dateCreated": string;
  /** Format: timestamp without time zone */
  "rowFilter.elrh_book.dateEdited": string;
  /** Format: character varying */
  "rowFilter.elrh_book.writer": string;
  /** Format: character varying */
  "rowFilter.elrh_book.name": string;
  /** Format: character varying */
  "rowFilter.elrh_book.dscr": string;
  /** Format: character varying */
  "rowFilter.elrh_book.url": string;
  /** Format: character varying */
  "rowFilter.elrh_book.thumb": string;
  /** Format: character varying */
  "rowFilter.elrh_book.review": string;
  /** Format: character varying */
  "rowFilter.elrh_book.year": string;
  /** Format: integer */
  "rowFilter.elrh_book.authorId": string;
}

export interface operations {}

export interface external {}
