# auto-merge changes from 'main' to deployment branch 'stara-krc'

name: Merge 'main' into deployment branch
run-name: "[Automated] Merge ${{ github.ref_name }} into ${{ vars.DEPLOYMENT_BRANCH }}"

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  main:
    name: Create PR to deployment
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MERGE_MAIN_ACCESS_TOKEN }}
      - name: create pull request
        id: open-pr
        run: gh pr create --base ${{ vars.DEPLOYMENT_BRANCH }} --title "[Automated] Merge ${{ github.ref_name }} into ${{ vars.DEPLOYMENT_BRANCH }}" --body "Automated Pull Request from 'main' into deployment branch"
        env:
          GH_TOKEN: ${{ secrets.MERGE_MAIN_ACCESS_TOKEN }}
      - name: enable automerge
        run: gh pr merge --merge --auto "${{ steps.open-pr.outputs.pr_number }}"
        env:
          GH_TOKEN: ${{ secrets.MERGE_MAIN_ACCESS_TOKEN }}
